// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: collections_service.proto
// Protobuf C++ Version: 6.33.0

#include "collections_service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace qdrant {
}  // namespace qdrant
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_collections_5fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_collections_5fservice_2eproto = nullptr;
const ::uint32_t TableStruct_collections_5fservice_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* PROTOBUF_NULLABLE schemas = nullptr;
static constexpr ::_pb::Message* PROTOBUF_NONNULL const* PROTOBUF_NULLABLE
    file_default_instances = nullptr;
const char descriptor_table_protodef_collections_5fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\031collections_service.proto\022\006qdrant\032\021col"
    "lections.proto2\342\010\n\013Collections\022L\n\003Get\022 ."
    "qdrant.GetCollectionInfoRequest\032!.qdrant"
    ".GetCollectionInfoResponse\"\000\022I\n\004List\022\036.q"
    "drant.ListCollectionsRequest\032\037.qdrant.Li"
    "stCollectionsResponse\"\000\022I\n\006Create\022\030.qdra"
    "nt.CreateCollection\032#.qdrant.CollectionO"
    "perationResponse\"\000\022I\n\006Update\022\030.qdrant.Up"
    "dateCollection\032#.qdrant.CollectionOperat"
    "ionResponse\"\000\022I\n\006Delete\022\030.qdrant.DeleteC"
    "ollection\032#.qdrant.CollectionOperationRe"
    "sponse\"\000\022M\n\rUpdateAliases\022\025.qdrant.Chang"
    "eAliases\032#.qdrant.CollectionOperationRes"
    "ponse\"\000\022\\\n\025ListCollectionAliases\022$.qdran"
    "t.ListCollectionAliasesRequest\032\033.qdrant."
    "ListAliasesResponse\"\000\022H\n\013ListAliases\022\032.q"
    "drant.ListAliasesRequest\032\033.qdrant.ListAl"
    "iasesResponse\"\000\022f\n\025CollectionClusterInfo"
    "\022$.qdrant.CollectionClusterInfoRequest\032%"
    ".qdrant.CollectionClusterInfoResponse\"\000\022"
    "W\n\020CollectionExists\022\037.qdrant.CollectionE"
    "xistsRequest\032 .qdrant.CollectionExistsRe"
    "sponse\"\000\022{\n\034UpdateCollectionClusterSetup"
    "\022+.qdrant.UpdateCollectionClusterSetupRe"
    "quest\032,.qdrant.UpdateCollectionClusterSe"
    "tupResponse\"\000\022Q\n\016CreateShardKey\022\035.qdrant"
    ".CreateShardKeyRequest\032\036.qdrant.CreateSh"
    "ardKeyResponse\"\000\022Q\n\016DeleteShardKey\022\035.qdr"
    "ant.DeleteShardKeyRequest\032\036.qdrant.Delet"
    "eShardKeyResponse\"\000B\025\252\002\022Qdrant.Client.Gr"
    "pcb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_collections_5fservice_2eproto_deps[1] = {
        &::descriptor_table_collections_2eproto,
};
static ::absl::once_flag descriptor_table_collections_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_collections_5fservice_2eproto = {
    false,
    false,
    1210,
    descriptor_table_protodef_collections_5fservice_2eproto,
    "collections_service.proto",
    &descriptor_table_collections_5fservice_2eproto_once,
    descriptor_table_collections_5fservice_2eproto_deps,
    1,
    0,
    schemas,
    file_default_instances,
    TableStruct_collections_5fservice_2eproto::offsets,
    file_level_enum_descriptors_collections_5fservice_2eproto,
    file_level_service_descriptors_collections_5fservice_2eproto,
};
namespace qdrant {
// @@protoc_insertion_point(namespace_scope)
}  // namespace qdrant
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_collections_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
