// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: points_service.proto
// Protobuf C++ Version: 6.33.0

#include "points_service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace qdrant {
}  // namespace qdrant
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_points_5fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_points_5fservice_2eproto = nullptr;
const ::uint32_t TableStruct_points_5fservice_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* PROTOBUF_NULLABLE schemas = nullptr;
static constexpr ::_pb::Message* PROTOBUF_NONNULL const* PROTOBUF_NULLABLE
    file_default_instances = nullptr;
const char descriptor_table_protodef_points_5fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024points_service.proto\022\006qdrant\032\014points.p"
    "roto2\375\017\n\006Points\022A\n\006Upsert\022\024.qdrant.Upser"
    "tPoints\032\037.qdrant.PointsOperationResponse"
    "\"\000\022A\n\006Delete\022\024.qdrant.DeletePoints\032\037.qdr"
    "ant.PointsOperationResponse\"\000\022/\n\003Get\022\021.q"
    "drant.GetPoints\032\023.qdrant.GetResponse\"\000\022N"
    "\n\rUpdateVectors\022\032.qdrant.UpdatePointVect"
    "ors\032\037.qdrant.PointsOperationResponse\"\000\022N"
    "\n\rDeleteVectors\022\032.qdrant.DeletePointVect"
    "ors\032\037.qdrant.PointsOperationResponse\"\000\022I"
    "\n\nSetPayload\022\030.qdrant.SetPayloadPoints\032\037"
    ".qdrant.PointsOperationResponse\"\000\022O\n\020Ove"
    "rwritePayload\022\030.qdrant.SetPayloadPoints\032"
    "\037.qdrant.PointsOperationResponse\"\000\022O\n\rDe"
    "letePayload\022\033.qdrant.DeletePayloadPoints"
    "\032\037.qdrant.PointsOperationResponse\"\000\022M\n\014C"
    "learPayload\022\032.qdrant.ClearPayloadPoints\032"
    "\037.qdrant.PointsOperationResponse\"\000\022Y\n\020Cr"
    "eateFieldIndex\022\".qdrant.CreateFieldIndex"
    "Collection\032\037.qdrant.PointsOperationRespo"
    "nse\"\000\022Y\n\020DeleteFieldIndex\022\".qdrant.Delet"
    "eFieldIndexCollection\032\037.qdrant.PointsOpe"
    "rationResponse\"\000\0228\n\006Search\022\024.qdrant.Sear"
    "chPoints\032\026.qdrant.SearchResponse\"\000\022G\n\013Se"
    "archBatch\022\031.qdrant.SearchBatchPoints\032\033.q"
    "drant.SearchBatchResponse\"\000\022I\n\014SearchGro"
    "ups\022\031.qdrant.SearchPointGroups\032\034.qdrant."
    "SearchGroupsResponse\"\000\0228\n\006Scroll\022\024.qdran"
    "t.ScrollPoints\032\026.qdrant.ScrollResponse\"\000"
    "\022A\n\tRecommend\022\027.qdrant.RecommendPoints\032\031"
    ".qdrant.RecommendResponse\"\000\022P\n\016Recommend"
    "Batch\022\034.qdrant.RecommendBatchPoints\032\036.qd"
    "rant.RecommendBatchResponse\"\000\022R\n\017Recomme"
    "ndGroups\022\034.qdrant.RecommendPointGroups\032\037"
    ".qdrant.RecommendGroupsResponse\"\000\022>\n\010Dis"
    "cover\022\026.qdrant.DiscoverPoints\032\030.qdrant.D"
    "iscoverResponse\"\000\022M\n\rDiscoverBatch\022\033.qdr"
    "ant.DiscoverBatchPoints\032\035.qdrant.Discove"
    "rBatchResponse\"\000\0225\n\005Count\022\023.qdrant.Count"
    "Points\032\025.qdrant.CountResponse\"\000\022G\n\013Updat"
    "eBatch\022\031.qdrant.UpdateBatchPoints\032\033.qdra"
    "nt.UpdateBatchResponse\"\000\0225\n\005Query\022\023.qdra"
    "nt.QueryPoints\032\025.qdrant.QueryResponse\"\000\022"
    "D\n\nQueryBatch\022\030.qdrant.QueryBatchPoints\032"
    "\032.qdrant.QueryBatchResponse\"\000\022F\n\013QueryGr"
    "oups\022\030.qdrant.QueryPointGroups\032\033.qdrant."
    "QueryGroupsResponse\"\000\0225\n\005Facet\022\023.qdrant."
    "FacetCounts\032\025.qdrant.FacetResponse\"\000\022T\n\021"
    "SearchMatrixPairs\022\032.qdrant.SearchMatrixP"
    "oints\032!.qdrant.SearchMatrixPairsResponse"
    "\"\000\022X\n\023SearchMatrixOffsets\022\032.qdrant.Searc"
    "hMatrixPoints\032#.qdrant.SearchMatrixOffse"
    "tsResponse\"\000B\025\252\002\022Qdrant.Client.Grpcb\006pro"
    "to3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_points_5fservice_2eproto_deps[1] = {
        &::descriptor_table_points_2eproto,
};
static ::absl::once_flag descriptor_table_points_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_points_5fservice_2eproto = {
    false,
    false,
    2123,
    descriptor_table_protodef_points_5fservice_2eproto,
    "points_service.proto",
    &descriptor_table_points_5fservice_2eproto_once,
    descriptor_table_points_5fservice_2eproto_deps,
    1,
    0,
    schemas,
    file_default_instances,
    TableStruct_points_5fservice_2eproto::offsets,
    file_level_enum_descriptors_points_5fservice_2eproto,
    file_level_service_descriptors_points_5fservice_2eproto,
};
namespace qdrant {
// @@protoc_insertion_point(namespace_scope)
}  // namespace qdrant
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_points_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
