// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: qdrant.proto
// Protobuf C++ Version: 6.33.0

#include "qdrant.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace qdrant {
template <typename>
PROTOBUF_CONSTEXPR HealthCheckRequest::HealthCheckRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(HealthCheckRequest_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct HealthCheckRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HealthCheckRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HealthCheckRequestDefaultTypeInternal() {}
  union {
    HealthCheckRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HealthCheckRequestDefaultTypeInternal _HealthCheckRequest_default_instance_;

inline constexpr HealthCheckReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        title_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        version_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        commit_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR HealthCheckReply::HealthCheckReply(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(HealthCheckReply_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct HealthCheckReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HealthCheckReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HealthCheckReplyDefaultTypeInternal() {}
  union {
    HealthCheckReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HealthCheckReplyDefaultTypeInternal _HealthCheckReply_default_instance_;
}  // namespace qdrant
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_qdrant_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_qdrant_2eproto = nullptr;
const ::uint32_t
    TableStruct_qdrant_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::qdrant::HealthCheckReply, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::qdrant::HealthCheckReply, _impl_.title_),
        PROTOBUF_FIELD_OFFSET(::qdrant::HealthCheckReply, _impl_.version_),
        PROTOBUF_FIELD_OFFSET(::qdrant::HealthCheckReply, _impl_.commit_),
        0,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::qdrant::HealthCheckRequest)},
        {1, sizeof(::qdrant::HealthCheckReply)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::qdrant::_HealthCheckRequest_default_instance_._instance,
    &::qdrant::_HealthCheckReply_default_instance_._instance,
};
const char descriptor_table_protodef_qdrant_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014qdrant.proto\022\006qdrant\032\031collections_serv"
    "ice.proto\032\"collections_internal_service."
    "proto\032\022health_check.proto\032\024points_servic"
    "e.proto\032\035points_internal_service.proto\032\035"
    "qdrant_internal_service.proto\032\022raft_serv"
    "ice.proto\032\035shard_snapshots_service.proto"
    "\032\027snapshots_service.proto\"\024\n\022HealthCheck"
    "Request\"R\n\020HealthCheckReply\022\r\n\005title\030\001 \001"
    "(\t\022\017\n\007version\030\002 \001(\t\022\023\n\006commit\030\003 \001(\tH\000\210\001\001"
    "B\t\n\007_commit2O\n\006Qdrant\022E\n\013HealthCheck\022\032.q"
    "drant.HealthCheckRequest\032\030.qdrant.Health"
    "CheckReply\"\000B\025\252\002\022Qdrant.Client.Grpcb\006pro"
    "to3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_qdrant_2eproto_deps[9] = {
        &::descriptor_table_collections_5finternal_5fservice_2eproto,
        &::descriptor_table_collections_5fservice_2eproto,
        &::descriptor_table_health_5fcheck_2eproto,
        &::descriptor_table_points_5finternal_5fservice_2eproto,
        &::descriptor_table_points_5fservice_2eproto,
        &::descriptor_table_qdrant_5finternal_5fservice_2eproto,
        &::descriptor_table_raft_5fservice_2eproto,
        &::descriptor_table_shard_5fsnapshots_5fservice_2eproto,
        &::descriptor_table_snapshots_5fservice_2eproto,
};
static ::absl::once_flag descriptor_table_qdrant_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_qdrant_2eproto = {
    false,
    false,
    483,
    descriptor_table_protodef_qdrant_2eproto,
    "qdrant.proto",
    &descriptor_table_qdrant_2eproto_once,
    descriptor_table_qdrant_2eproto_deps,
    9,
    2,
    schemas,
    file_default_instances,
    TableStruct_qdrant_2eproto::offsets,
    file_level_enum_descriptors_qdrant_2eproto,
    file_level_service_descriptors_qdrant_2eproto,
};
namespace qdrant {
// ===================================================================

class HealthCheckRequest::_Internal {
 public:
};

HealthCheckRequest::HealthCheckRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, HealthCheckRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:qdrant.HealthCheckRequest)
}
HealthCheckRequest::HealthCheckRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const HealthCheckRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, HealthCheckRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  HealthCheckRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:qdrant.HealthCheckRequest)
}

inline void* PROTOBUF_NONNULL HealthCheckRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) HealthCheckRequest(arena);
}
constexpr auto HealthCheckRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(HealthCheckRequest),
                                            alignof(HealthCheckRequest));
}
constexpr auto HealthCheckRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_HealthCheckRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &HealthCheckRequest::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<HealthCheckRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &HealthCheckRequest::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<HealthCheckRequest>(), &HealthCheckRequest::ByteSizeLong,
              &HealthCheckRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(HealthCheckRequest, _impl_._cached_size_),
          false,
      },
      &HealthCheckRequest::kDescriptorMethods,
      &descriptor_table_qdrant_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull HealthCheckRequest_class_data_ =
        HealthCheckRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
HealthCheckRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&HealthCheckRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(HealthCheckRequest_class_data_.tc_table);
  return HealthCheckRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
HealthCheckRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    HealthCheckRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::qdrant::HealthCheckRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata HealthCheckRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class HealthCheckReply::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<HealthCheckReply>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(HealthCheckReply, _impl_._has_bits_);
};

HealthCheckReply::HealthCheckReply(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HealthCheckReply_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:qdrant.HealthCheckReply)
}
PROTOBUF_NDEBUG_INLINE HealthCheckReply::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::qdrant::HealthCheckReply& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        title_(arena, from.title_),
        version_(arena, from.version_),
        commit_(arena, from.commit_) {}

HealthCheckReply::HealthCheckReply(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const HealthCheckReply& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, HealthCheckReply_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  HealthCheckReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:qdrant.HealthCheckReply)
}
PROTOBUF_NDEBUG_INLINE HealthCheckReply::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        title_(arena),
        version_(arena),
        commit_(arena) {}

inline void HealthCheckReply::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
HealthCheckReply::~HealthCheckReply() {
  // @@protoc_insertion_point(destructor:qdrant.HealthCheckReply)
  SharedDtor(*this);
}
inline void HealthCheckReply::SharedDtor(MessageLite& self) {
  HealthCheckReply& this_ = static_cast<HealthCheckReply&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.title_.Destroy();
  this_._impl_.version_.Destroy();
  this_._impl_.commit_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL HealthCheckReply::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) HealthCheckReply(arena);
}
constexpr auto HealthCheckReply::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(HealthCheckReply),
                                            alignof(HealthCheckReply));
}
constexpr auto HealthCheckReply::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_HealthCheckReply_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &HealthCheckReply::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<HealthCheckReply>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &HealthCheckReply::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<HealthCheckReply>(), &HealthCheckReply::ByteSizeLong,
              &HealthCheckReply::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(HealthCheckReply, _impl_._cached_size_),
          false,
      },
      &HealthCheckReply::kDescriptorMethods,
      &descriptor_table_qdrant_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull HealthCheckReply_class_data_ =
        HealthCheckReply::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
HealthCheckReply::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&HealthCheckReply_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(HealthCheckReply_class_data_.tc_table);
  return HealthCheckReply_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 50, 2>
HealthCheckReply::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(HealthCheckReply, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    HealthCheckReply_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::qdrant::HealthCheckReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string title = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(HealthCheckReply, _impl_.title_)}},
    // string version = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(HealthCheckReply, _impl_.version_)}},
    // optional string commit = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0,
      PROTOBUF_FIELD_OFFSET(HealthCheckReply, _impl_.commit_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string title = 1;
    {PROTOBUF_FIELD_OFFSET(HealthCheckReply, _impl_.title_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string version = 2;
    {PROTOBUF_FIELD_OFFSET(HealthCheckReply, _impl_.version_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string commit = 3;
    {PROTOBUF_FIELD_OFFSET(HealthCheckReply, _impl_.commit_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\5\7\6\0\0\0\0"
    "qdrant.HealthCheckReply"
    "title"
    "version"
    "commit"
  }},
};
PROTOBUF_NOINLINE void HealthCheckReply::Clear() {
// @@protoc_insertion_point(message_clear_start:qdrant.HealthCheckReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.title_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.version_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.commit_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL HealthCheckReply::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const HealthCheckReply& this_ = static_cast<const HealthCheckReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL HealthCheckReply::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const HealthCheckReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:qdrant.HealthCheckReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string title = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_title().empty()) {
      const ::std::string& _s = this_._internal_title();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "qdrant.HealthCheckReply.title");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string version = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_version().empty()) {
      const ::std::string& _s = this_._internal_version();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "qdrant.HealthCheckReply.version");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // optional string commit = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    const ::std::string& _s = this_._internal_commit();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "qdrant.HealthCheckReply.commit");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:qdrant.HealthCheckReply)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t HealthCheckReply::ByteSizeLong(const MessageLite& base) {
  const HealthCheckReply& this_ = static_cast<const HealthCheckReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t HealthCheckReply::ByteSizeLong() const {
  const HealthCheckReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:qdrant.HealthCheckReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // string title = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_title().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_title());
      }
    }
    // string version = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_version().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_version());
      }
    }
    // optional string commit = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_commit());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void HealthCheckReply::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<HealthCheckReply*>(&to_msg);
  auto& from = static_cast<const HealthCheckReply&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:qdrant.HealthCheckReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_title().empty()) {
        _this->_internal_set_title(from._internal_title());
      } else {
        if (_this->_impl_.title_.IsDefault()) {
          _this->_internal_set_title("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_version().empty()) {
        _this->_internal_set_version(from._internal_version());
      } else {
        if (_this->_impl_.version_.IsDefault()) {
          _this->_internal_set_version("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_internal_set_commit(from._internal_commit());
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void HealthCheckReply::CopyFrom(const HealthCheckReply& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:qdrant.HealthCheckReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void HealthCheckReply::InternalSwap(HealthCheckReply* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.title_, &other->_impl_.title_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.version_, &other->_impl_.version_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.commit_, &other->_impl_.commit_, arena);
}

::google::protobuf::Metadata HealthCheckReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace qdrant
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_qdrant_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
