// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: qdrant_internal_service.proto
// Protobuf C++ Version: 6.33.0

#include "qdrant_internal_service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace qdrant {

inline constexpr WaitOnConsensusCommitResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ok_{false} {}

template <typename>
PROTOBUF_CONSTEXPR WaitOnConsensusCommitResponse::WaitOnConsensusCommitResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(WaitOnConsensusCommitResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WaitOnConsensusCommitResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WaitOnConsensusCommitResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WaitOnConsensusCommitResponseDefaultTypeInternal() {}
  union {
    WaitOnConsensusCommitResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WaitOnConsensusCommitResponseDefaultTypeInternal _WaitOnConsensusCommitResponse_default_instance_;

inline constexpr WaitOnConsensusCommitRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        commit_{::int64_t{0}},
        term_{::int64_t{0}},
        timeout_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR WaitOnConsensusCommitRequest::WaitOnConsensusCommitRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(WaitOnConsensusCommitRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct WaitOnConsensusCommitRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WaitOnConsensusCommitRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WaitOnConsensusCommitRequestDefaultTypeInternal() {}
  union {
    WaitOnConsensusCommitRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WaitOnConsensusCommitRequestDefaultTypeInternal _WaitOnConsensusCommitRequest_default_instance_;

inline constexpr GetConsensusCommitResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        commit_{::int64_t{0}},
        term_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR GetConsensusCommitResponse::GetConsensusCommitResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(GetConsensusCommitResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetConsensusCommitResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetConsensusCommitResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetConsensusCommitResponseDefaultTypeInternal() {}
  union {
    GetConsensusCommitResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetConsensusCommitResponseDefaultTypeInternal _GetConsensusCommitResponse_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR GetConsensusCommitRequest::GetConsensusCommitRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(GetConsensusCommitRequest_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct GetConsensusCommitRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetConsensusCommitRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetConsensusCommitRequestDefaultTypeInternal() {}
  union {
    GetConsensusCommitRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetConsensusCommitRequestDefaultTypeInternal _GetConsensusCommitRequest_default_instance_;
}  // namespace qdrant
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_qdrant_5finternal_5fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_qdrant_5finternal_5fservice_2eproto = nullptr;
const ::uint32_t
    TableStruct_qdrant_5finternal_5fservice_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::qdrant::GetConsensusCommitResponse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::qdrant::GetConsensusCommitResponse, _impl_.commit_),
        PROTOBUF_FIELD_OFFSET(::qdrant::GetConsensusCommitResponse, _impl_.term_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::qdrant::WaitOnConsensusCommitRequest, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::qdrant::WaitOnConsensusCommitRequest, _impl_.commit_),
        PROTOBUF_FIELD_OFFSET(::qdrant::WaitOnConsensusCommitRequest, _impl_.term_),
        PROTOBUF_FIELD_OFFSET(::qdrant::WaitOnConsensusCommitRequest, _impl_.timeout_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::qdrant::WaitOnConsensusCommitResponse, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::qdrant::WaitOnConsensusCommitResponse, _impl_.ok_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::qdrant::GetConsensusCommitRequest)},
        {1, sizeof(::qdrant::GetConsensusCommitResponse)},
        {8, sizeof(::qdrant::WaitOnConsensusCommitRequest)},
        {17, sizeof(::qdrant::WaitOnConsensusCommitResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::qdrant::_GetConsensusCommitRequest_default_instance_._instance,
    &::qdrant::_GetConsensusCommitResponse_default_instance_._instance,
    &::qdrant::_WaitOnConsensusCommitRequest_default_instance_._instance,
    &::qdrant::_WaitOnConsensusCommitResponse_default_instance_._instance,
};
const char descriptor_table_protodef_qdrant_5finternal_5fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\035qdrant_internal_service.proto\022\006qdrant\""
    "\033\n\031GetConsensusCommitRequest\":\n\032GetConse"
    "nsusCommitResponse\022\016\n\006commit\030\001 \001(\003\022\014\n\004te"
    "rm\030\002 \001(\003\"M\n\034WaitOnConsensusCommitRequest"
    "\022\016\n\006commit\030\001 \001(\003\022\014\n\004term\030\002 \001(\003\022\017\n\007timeou"
    "t\030\003 \001(\003\"+\n\035WaitOnConsensusCommitResponse"
    "\022\n\n\002ok\030\001 \001(\0102\327\001\n\016QdrantInternal\022]\n\022GetCo"
    "nsensusCommit\022!.qdrant.GetConsensusCommi"
    "tRequest\032\".qdrant.GetConsensusCommitResp"
    "onse\"\000\022f\n\025WaitOnConsensusCommit\022$.qdrant"
    ".WaitOnConsensusCommitRequest\032%.qdrant.W"
    "aitOnConsensusCommitResponse\"\000B\025\252\002\022Qdran"
    "t.Client.Grpcb\006proto3"
};
static ::absl::once_flag descriptor_table_qdrant_5finternal_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_qdrant_5finternal_5fservice_2eproto = {
    false,
    false,
    501,
    descriptor_table_protodef_qdrant_5finternal_5fservice_2eproto,
    "qdrant_internal_service.proto",
    &descriptor_table_qdrant_5finternal_5fservice_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_qdrant_5finternal_5fservice_2eproto::offsets,
    file_level_enum_descriptors_qdrant_5finternal_5fservice_2eproto,
    file_level_service_descriptors_qdrant_5finternal_5fservice_2eproto,
};
namespace qdrant {
// ===================================================================

class GetConsensusCommitRequest::_Internal {
 public:
};

GetConsensusCommitRequest::GetConsensusCommitRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, GetConsensusCommitRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:qdrant.GetConsensusCommitRequest)
}
GetConsensusCommitRequest::GetConsensusCommitRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GetConsensusCommitRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, GetConsensusCommitRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetConsensusCommitRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:qdrant.GetConsensusCommitRequest)
}

inline void* PROTOBUF_NONNULL GetConsensusCommitRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GetConsensusCommitRequest(arena);
}
constexpr auto GetConsensusCommitRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GetConsensusCommitRequest),
                                            alignof(GetConsensusCommitRequest));
}
constexpr auto GetConsensusCommitRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GetConsensusCommitRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &GetConsensusCommitRequest::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<GetConsensusCommitRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GetConsensusCommitRequest::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<GetConsensusCommitRequest>(), &GetConsensusCommitRequest::ByteSizeLong,
              &GetConsensusCommitRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GetConsensusCommitRequest, _impl_._cached_size_),
          false,
      },
      &GetConsensusCommitRequest::kDescriptorMethods,
      &descriptor_table_qdrant_5finternal_5fservice_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GetConsensusCommitRequest_class_data_ =
        GetConsensusCommitRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GetConsensusCommitRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GetConsensusCommitRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GetConsensusCommitRequest_class_data_.tc_table);
  return GetConsensusCommitRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
GetConsensusCommitRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    GetConsensusCommitRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::qdrant::GetConsensusCommitRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata GetConsensusCommitRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetConsensusCommitResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GetConsensusCommitResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GetConsensusCommitResponse, _impl_._has_bits_);
};

GetConsensusCommitResponse::GetConsensusCommitResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetConsensusCommitResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:qdrant.GetConsensusCommitResponse)
}
GetConsensusCommitResponse::GetConsensusCommitResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GetConsensusCommitResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetConsensusCommitResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE GetConsensusCommitResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void GetConsensusCommitResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, commit_),
           0,
           offsetof(Impl_, term_) -
               offsetof(Impl_, commit_) +
               sizeof(Impl_::term_));
}
GetConsensusCommitResponse::~GetConsensusCommitResponse() {
  // @@protoc_insertion_point(destructor:qdrant.GetConsensusCommitResponse)
  SharedDtor(*this);
}
inline void GetConsensusCommitResponse::SharedDtor(MessageLite& self) {
  GetConsensusCommitResponse& this_ = static_cast<GetConsensusCommitResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GetConsensusCommitResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GetConsensusCommitResponse(arena);
}
constexpr auto GetConsensusCommitResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GetConsensusCommitResponse),
                                            alignof(GetConsensusCommitResponse));
}
constexpr auto GetConsensusCommitResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GetConsensusCommitResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &GetConsensusCommitResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<GetConsensusCommitResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GetConsensusCommitResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<GetConsensusCommitResponse>(), &GetConsensusCommitResponse::ByteSizeLong,
              &GetConsensusCommitResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GetConsensusCommitResponse, _impl_._cached_size_),
          false,
      },
      &GetConsensusCommitResponse::kDescriptorMethods,
      &descriptor_table_qdrant_5finternal_5fservice_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GetConsensusCommitResponse_class_data_ =
        GetConsensusCommitResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GetConsensusCommitResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GetConsensusCommitResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GetConsensusCommitResponse_class_data_.tc_table);
  return GetConsensusCommitResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
GetConsensusCommitResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GetConsensusCommitResponse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    GetConsensusCommitResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::qdrant::GetConsensusCommitResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 term = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(GetConsensusCommitResponse, _impl_.term_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(GetConsensusCommitResponse, _impl_.term_)}},
    // int64 commit = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(GetConsensusCommitResponse, _impl_.commit_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(GetConsensusCommitResponse, _impl_.commit_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 commit = 1;
    {PROTOBUF_FIELD_OFFSET(GetConsensusCommitResponse, _impl_.commit_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // int64 term = 2;
    {PROTOBUF_FIELD_OFFSET(GetConsensusCommitResponse, _impl_.term_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void GetConsensusCommitResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:qdrant.GetConsensusCommitResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    ::memset(&_impl_.commit_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.term_) -
        reinterpret_cast<char*>(&_impl_.commit_)) + sizeof(_impl_.term_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GetConsensusCommitResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GetConsensusCommitResponse& this_ = static_cast<const GetConsensusCommitResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GetConsensusCommitResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GetConsensusCommitResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:qdrant.GetConsensusCommitResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int64 commit = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_commit() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
              stream, this_._internal_commit(), target);
    }
  }

  // int64 term = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_term() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_term(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:qdrant.GetConsensusCommitResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GetConsensusCommitResponse::ByteSizeLong(const MessageLite& base) {
  const GetConsensusCommitResponse& this_ = static_cast<const GetConsensusCommitResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GetConsensusCommitResponse::ByteSizeLong() const {
  const GetConsensusCommitResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:qdrant.GetConsensusCommitResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // int64 commit = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_commit() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_commit());
      }
    }
    // int64 term = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_term() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_term());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void GetConsensusCommitResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<GetConsensusCommitResponse*>(&to_msg);
  auto& from = static_cast<const GetConsensusCommitResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:qdrant.GetConsensusCommitResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_commit() != 0) {
        _this->_impl_.commit_ = from._impl_.commit_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_term() != 0) {
        _this->_impl_.term_ = from._impl_.term_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void GetConsensusCommitResponse::CopyFrom(const GetConsensusCommitResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:qdrant.GetConsensusCommitResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetConsensusCommitResponse::InternalSwap(GetConsensusCommitResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetConsensusCommitResponse, _impl_.term_)
      + sizeof(GetConsensusCommitResponse::_impl_.term_)
      - PROTOBUF_FIELD_OFFSET(GetConsensusCommitResponse, _impl_.commit_)>(
          reinterpret_cast<char*>(&_impl_.commit_),
          reinterpret_cast<char*>(&other->_impl_.commit_));
}

::google::protobuf::Metadata GetConsensusCommitResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class WaitOnConsensusCommitRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<WaitOnConsensusCommitRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(WaitOnConsensusCommitRequest, _impl_._has_bits_);
};

WaitOnConsensusCommitRequest::WaitOnConsensusCommitRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WaitOnConsensusCommitRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:qdrant.WaitOnConsensusCommitRequest)
}
WaitOnConsensusCommitRequest::WaitOnConsensusCommitRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const WaitOnConsensusCommitRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WaitOnConsensusCommitRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE WaitOnConsensusCommitRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void WaitOnConsensusCommitRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, commit_),
           0,
           offsetof(Impl_, timeout_) -
               offsetof(Impl_, commit_) +
               sizeof(Impl_::timeout_));
}
WaitOnConsensusCommitRequest::~WaitOnConsensusCommitRequest() {
  // @@protoc_insertion_point(destructor:qdrant.WaitOnConsensusCommitRequest)
  SharedDtor(*this);
}
inline void WaitOnConsensusCommitRequest::SharedDtor(MessageLite& self) {
  WaitOnConsensusCommitRequest& this_ = static_cast<WaitOnConsensusCommitRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL WaitOnConsensusCommitRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) WaitOnConsensusCommitRequest(arena);
}
constexpr auto WaitOnConsensusCommitRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(WaitOnConsensusCommitRequest),
                                            alignof(WaitOnConsensusCommitRequest));
}
constexpr auto WaitOnConsensusCommitRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_WaitOnConsensusCommitRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &WaitOnConsensusCommitRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<WaitOnConsensusCommitRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &WaitOnConsensusCommitRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<WaitOnConsensusCommitRequest>(), &WaitOnConsensusCommitRequest::ByteSizeLong,
              &WaitOnConsensusCommitRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(WaitOnConsensusCommitRequest, _impl_._cached_size_),
          false,
      },
      &WaitOnConsensusCommitRequest::kDescriptorMethods,
      &descriptor_table_qdrant_5finternal_5fservice_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull WaitOnConsensusCommitRequest_class_data_ =
        WaitOnConsensusCommitRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
WaitOnConsensusCommitRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&WaitOnConsensusCommitRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(WaitOnConsensusCommitRequest_class_data_.tc_table);
  return WaitOnConsensusCommitRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
WaitOnConsensusCommitRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(WaitOnConsensusCommitRequest, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    WaitOnConsensusCommitRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::qdrant::WaitOnConsensusCommitRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int64 commit = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(WaitOnConsensusCommitRequest, _impl_.commit_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(WaitOnConsensusCommitRequest, _impl_.commit_)}},
    // int64 term = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(WaitOnConsensusCommitRequest, _impl_.term_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(WaitOnConsensusCommitRequest, _impl_.term_)}},
    // int64 timeout = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(WaitOnConsensusCommitRequest, _impl_.timeout_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(WaitOnConsensusCommitRequest, _impl_.timeout_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 commit = 1;
    {PROTOBUF_FIELD_OFFSET(WaitOnConsensusCommitRequest, _impl_.commit_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // int64 term = 2;
    {PROTOBUF_FIELD_OFFSET(WaitOnConsensusCommitRequest, _impl_.term_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // int64 timeout = 3;
    {PROTOBUF_FIELD_OFFSET(WaitOnConsensusCommitRequest, _impl_.timeout_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void WaitOnConsensusCommitRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:qdrant.WaitOnConsensusCommitRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    ::memset(&_impl_.commit_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.timeout_) -
        reinterpret_cast<char*>(&_impl_.commit_)) + sizeof(_impl_.timeout_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL WaitOnConsensusCommitRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const WaitOnConsensusCommitRequest& this_ = static_cast<const WaitOnConsensusCommitRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL WaitOnConsensusCommitRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const WaitOnConsensusCommitRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:qdrant.WaitOnConsensusCommitRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int64 commit = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_commit() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
              stream, this_._internal_commit(), target);
    }
  }

  // int64 term = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_term() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_term(), target);
    }
  }

  // int64 timeout = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_timeout() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<3>(
              stream, this_._internal_timeout(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:qdrant.WaitOnConsensusCommitRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t WaitOnConsensusCommitRequest::ByteSizeLong(const MessageLite& base) {
  const WaitOnConsensusCommitRequest& this_ = static_cast<const WaitOnConsensusCommitRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t WaitOnConsensusCommitRequest::ByteSizeLong() const {
  const WaitOnConsensusCommitRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:qdrant.WaitOnConsensusCommitRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // int64 commit = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_commit() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_commit());
      }
    }
    // int64 term = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_term() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_term());
      }
    }
    // int64 timeout = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_timeout() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_timeout());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void WaitOnConsensusCommitRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<WaitOnConsensusCommitRequest*>(&to_msg);
  auto& from = static_cast<const WaitOnConsensusCommitRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:qdrant.WaitOnConsensusCommitRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_commit() != 0) {
        _this->_impl_.commit_ = from._impl_.commit_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_term() != 0) {
        _this->_impl_.term_ = from._impl_.term_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_timeout() != 0) {
        _this->_impl_.timeout_ = from._impl_.timeout_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void WaitOnConsensusCommitRequest::CopyFrom(const WaitOnConsensusCommitRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:qdrant.WaitOnConsensusCommitRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WaitOnConsensusCommitRequest::InternalSwap(WaitOnConsensusCommitRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WaitOnConsensusCommitRequest, _impl_.timeout_)
      + sizeof(WaitOnConsensusCommitRequest::_impl_.timeout_)
      - PROTOBUF_FIELD_OFFSET(WaitOnConsensusCommitRequest, _impl_.commit_)>(
          reinterpret_cast<char*>(&_impl_.commit_),
          reinterpret_cast<char*>(&other->_impl_.commit_));
}

::google::protobuf::Metadata WaitOnConsensusCommitRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class WaitOnConsensusCommitResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<WaitOnConsensusCommitResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(WaitOnConsensusCommitResponse, _impl_._has_bits_);
};

WaitOnConsensusCommitResponse::WaitOnConsensusCommitResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WaitOnConsensusCommitResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:qdrant.WaitOnConsensusCommitResponse)
}
WaitOnConsensusCommitResponse::WaitOnConsensusCommitResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const WaitOnConsensusCommitResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, WaitOnConsensusCommitResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE WaitOnConsensusCommitResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void WaitOnConsensusCommitResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.ok_ = {};
}
WaitOnConsensusCommitResponse::~WaitOnConsensusCommitResponse() {
  // @@protoc_insertion_point(destructor:qdrant.WaitOnConsensusCommitResponse)
  SharedDtor(*this);
}
inline void WaitOnConsensusCommitResponse::SharedDtor(MessageLite& self) {
  WaitOnConsensusCommitResponse& this_ = static_cast<WaitOnConsensusCommitResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL WaitOnConsensusCommitResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) WaitOnConsensusCommitResponse(arena);
}
constexpr auto WaitOnConsensusCommitResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(WaitOnConsensusCommitResponse),
                                            alignof(WaitOnConsensusCommitResponse));
}
constexpr auto WaitOnConsensusCommitResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_WaitOnConsensusCommitResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &WaitOnConsensusCommitResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<WaitOnConsensusCommitResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &WaitOnConsensusCommitResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<WaitOnConsensusCommitResponse>(), &WaitOnConsensusCommitResponse::ByteSizeLong,
              &WaitOnConsensusCommitResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(WaitOnConsensusCommitResponse, _impl_._cached_size_),
          false,
      },
      &WaitOnConsensusCommitResponse::kDescriptorMethods,
      &descriptor_table_qdrant_5finternal_5fservice_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull WaitOnConsensusCommitResponse_class_data_ =
        WaitOnConsensusCommitResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
WaitOnConsensusCommitResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&WaitOnConsensusCommitResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(WaitOnConsensusCommitResponse_class_data_.tc_table);
  return WaitOnConsensusCommitResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
WaitOnConsensusCommitResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(WaitOnConsensusCommitResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    WaitOnConsensusCommitResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::qdrant::WaitOnConsensusCommitResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool ok = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(WaitOnConsensusCommitResponse, _impl_.ok_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(WaitOnConsensusCommitResponse, _impl_.ok_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool ok = 1;
    {PROTOBUF_FIELD_OFFSET(WaitOnConsensusCommitResponse, _impl_.ok_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void WaitOnConsensusCommitResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:qdrant.WaitOnConsensusCommitResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ok_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL WaitOnConsensusCommitResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const WaitOnConsensusCommitResponse& this_ = static_cast<const WaitOnConsensusCommitResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL WaitOnConsensusCommitResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const WaitOnConsensusCommitResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:qdrant.WaitOnConsensusCommitResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bool ok = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_ok() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_ok(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:qdrant.WaitOnConsensusCommitResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t WaitOnConsensusCommitResponse::ByteSizeLong(const MessageLite& base) {
  const WaitOnConsensusCommitResponse& this_ = static_cast<const WaitOnConsensusCommitResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t WaitOnConsensusCommitResponse::ByteSizeLong() const {
  const WaitOnConsensusCommitResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:qdrant.WaitOnConsensusCommitResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // bool ok = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_ok() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void WaitOnConsensusCommitResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<WaitOnConsensusCommitResponse*>(&to_msg);
  auto& from = static_cast<const WaitOnConsensusCommitResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:qdrant.WaitOnConsensusCommitResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_ok() != 0) {
      _this->_impl_.ok_ = from._impl_.ok_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void WaitOnConsensusCommitResponse::CopyFrom(const WaitOnConsensusCommitResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:qdrant.WaitOnConsensusCommitResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void WaitOnConsensusCommitResponse::InternalSwap(WaitOnConsensusCommitResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.ok_, other->_impl_.ok_);
}

::google::protobuf::Metadata WaitOnConsensusCommitResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace qdrant
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_qdrant_5finternal_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
