// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: qdrant_internal_service.proto
// Protobuf C++ Version: 6.33.0

#ifndef qdrant_5finternal_5fservice_2eproto_2epb_2eh
#define qdrant_5finternal_5fservice_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_qdrant_5finternal_5fservice_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_qdrant_5finternal_5fservice_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_qdrant_5finternal_5fservice_2eproto;
}  // extern "C"
namespace qdrant {
class GetConsensusCommitRequest;
struct GetConsensusCommitRequestDefaultTypeInternal;
extern GetConsensusCommitRequestDefaultTypeInternal _GetConsensusCommitRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GetConsensusCommitRequest_class_data_;
class GetConsensusCommitResponse;
struct GetConsensusCommitResponseDefaultTypeInternal;
extern GetConsensusCommitResponseDefaultTypeInternal _GetConsensusCommitResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GetConsensusCommitResponse_class_data_;
class WaitOnConsensusCommitRequest;
struct WaitOnConsensusCommitRequestDefaultTypeInternal;
extern WaitOnConsensusCommitRequestDefaultTypeInternal _WaitOnConsensusCommitRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull WaitOnConsensusCommitRequest_class_data_;
class WaitOnConsensusCommitResponse;
struct WaitOnConsensusCommitResponseDefaultTypeInternal;
extern WaitOnConsensusCommitResponseDefaultTypeInternal _WaitOnConsensusCommitResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull WaitOnConsensusCommitResponse_class_data_;
}  // namespace qdrant
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace qdrant {

// ===================================================================


// -------------------------------------------------------------------

class WaitOnConsensusCommitResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:qdrant.WaitOnConsensusCommitResponse) */ {
 public:
  inline WaitOnConsensusCommitResponse() : WaitOnConsensusCommitResponse(nullptr) {}
  ~WaitOnConsensusCommitResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(WaitOnConsensusCommitResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(WaitOnConsensusCommitResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR WaitOnConsensusCommitResponse(::google::protobuf::internal::ConstantInitialized);

  inline WaitOnConsensusCommitResponse(const WaitOnConsensusCommitResponse& from) : WaitOnConsensusCommitResponse(nullptr, from) {}
  inline WaitOnConsensusCommitResponse(WaitOnConsensusCommitResponse&& from) noexcept
      : WaitOnConsensusCommitResponse(nullptr, ::std::move(from)) {}
  inline WaitOnConsensusCommitResponse& operator=(const WaitOnConsensusCommitResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline WaitOnConsensusCommitResponse& operator=(WaitOnConsensusCommitResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WaitOnConsensusCommitResponse& default_instance() {
    return *reinterpret_cast<const WaitOnConsensusCommitResponse*>(
        &_WaitOnConsensusCommitResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(WaitOnConsensusCommitResponse& a, WaitOnConsensusCommitResponse& b) { a.Swap(&b); }
  inline void Swap(WaitOnConsensusCommitResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WaitOnConsensusCommitResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WaitOnConsensusCommitResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<WaitOnConsensusCommitResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const WaitOnConsensusCommitResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const WaitOnConsensusCommitResponse& from) { WaitOnConsensusCommitResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(WaitOnConsensusCommitResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "qdrant.WaitOnConsensusCommitResponse"; }

  explicit WaitOnConsensusCommitResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  WaitOnConsensusCommitResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const WaitOnConsensusCommitResponse& from);
  WaitOnConsensusCommitResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, WaitOnConsensusCommitResponse&& from) noexcept
      : WaitOnConsensusCommitResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kOkFieldNumber = 1,
  };
  // bool ok = 1;
  void clear_ok() ;
  bool ok() const;
  void set_ok(bool value);

  private:
  bool _internal_ok() const;
  void _internal_set_ok(bool value);

  public:
  // @@protoc_insertion_point(class_scope:qdrant.WaitOnConsensusCommitResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const WaitOnConsensusCommitResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    bool ok_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_qdrant_5finternal_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull WaitOnConsensusCommitResponse_class_data_;
// -------------------------------------------------------------------

class WaitOnConsensusCommitRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:qdrant.WaitOnConsensusCommitRequest) */ {
 public:
  inline WaitOnConsensusCommitRequest() : WaitOnConsensusCommitRequest(nullptr) {}
  ~WaitOnConsensusCommitRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(WaitOnConsensusCommitRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(WaitOnConsensusCommitRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR WaitOnConsensusCommitRequest(::google::protobuf::internal::ConstantInitialized);

  inline WaitOnConsensusCommitRequest(const WaitOnConsensusCommitRequest& from) : WaitOnConsensusCommitRequest(nullptr, from) {}
  inline WaitOnConsensusCommitRequest(WaitOnConsensusCommitRequest&& from) noexcept
      : WaitOnConsensusCommitRequest(nullptr, ::std::move(from)) {}
  inline WaitOnConsensusCommitRequest& operator=(const WaitOnConsensusCommitRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline WaitOnConsensusCommitRequest& operator=(WaitOnConsensusCommitRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WaitOnConsensusCommitRequest& default_instance() {
    return *reinterpret_cast<const WaitOnConsensusCommitRequest*>(
        &_WaitOnConsensusCommitRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(WaitOnConsensusCommitRequest& a, WaitOnConsensusCommitRequest& b) { a.Swap(&b); }
  inline void Swap(WaitOnConsensusCommitRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WaitOnConsensusCommitRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WaitOnConsensusCommitRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<WaitOnConsensusCommitRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const WaitOnConsensusCommitRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const WaitOnConsensusCommitRequest& from) { WaitOnConsensusCommitRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(WaitOnConsensusCommitRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "qdrant.WaitOnConsensusCommitRequest"; }

  explicit WaitOnConsensusCommitRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  WaitOnConsensusCommitRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const WaitOnConsensusCommitRequest& from);
  WaitOnConsensusCommitRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, WaitOnConsensusCommitRequest&& from) noexcept
      : WaitOnConsensusCommitRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCommitFieldNumber = 1,
    kTermFieldNumber = 2,
    kTimeoutFieldNumber = 3,
  };
  // int64 commit = 1;
  void clear_commit() ;
  ::int64_t commit() const;
  void set_commit(::int64_t value);

  private:
  ::int64_t _internal_commit() const;
  void _internal_set_commit(::int64_t value);

  public:
  // int64 term = 2;
  void clear_term() ;
  ::int64_t term() const;
  void set_term(::int64_t value);

  private:
  ::int64_t _internal_term() const;
  void _internal_set_term(::int64_t value);

  public:
  // int64 timeout = 3;
  void clear_timeout() ;
  ::int64_t timeout() const;
  void set_timeout(::int64_t value);

  private:
  ::int64_t _internal_timeout() const;
  void _internal_set_timeout(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:qdrant.WaitOnConsensusCommitRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const WaitOnConsensusCommitRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t commit_;
    ::int64_t term_;
    ::int64_t timeout_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_qdrant_5finternal_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull WaitOnConsensusCommitRequest_class_data_;
// -------------------------------------------------------------------

class GetConsensusCommitResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:qdrant.GetConsensusCommitResponse) */ {
 public:
  inline GetConsensusCommitResponse() : GetConsensusCommitResponse(nullptr) {}
  ~GetConsensusCommitResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GetConsensusCommitResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GetConsensusCommitResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetConsensusCommitResponse(::google::protobuf::internal::ConstantInitialized);

  inline GetConsensusCommitResponse(const GetConsensusCommitResponse& from) : GetConsensusCommitResponse(nullptr, from) {}
  inline GetConsensusCommitResponse(GetConsensusCommitResponse&& from) noexcept
      : GetConsensusCommitResponse(nullptr, ::std::move(from)) {}
  inline GetConsensusCommitResponse& operator=(const GetConsensusCommitResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetConsensusCommitResponse& operator=(GetConsensusCommitResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetConsensusCommitResponse& default_instance() {
    return *reinterpret_cast<const GetConsensusCommitResponse*>(
        &_GetConsensusCommitResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(GetConsensusCommitResponse& a, GetConsensusCommitResponse& b) { a.Swap(&b); }
  inline void Swap(GetConsensusCommitResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetConsensusCommitResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetConsensusCommitResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GetConsensusCommitResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GetConsensusCommitResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GetConsensusCommitResponse& from) { GetConsensusCommitResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GetConsensusCommitResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "qdrant.GetConsensusCommitResponse"; }

  explicit GetConsensusCommitResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GetConsensusCommitResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GetConsensusCommitResponse& from);
  GetConsensusCommitResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GetConsensusCommitResponse&& from) noexcept
      : GetConsensusCommitResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCommitFieldNumber = 1,
    kTermFieldNumber = 2,
  };
  // int64 commit = 1;
  void clear_commit() ;
  ::int64_t commit() const;
  void set_commit(::int64_t value);

  private:
  ::int64_t _internal_commit() const;
  void _internal_set_commit(::int64_t value);

  public:
  // int64 term = 2;
  void clear_term() ;
  ::int64_t term() const;
  void set_term(::int64_t value);

  private:
  ::int64_t _internal_term() const;
  void _internal_set_term(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:qdrant.GetConsensusCommitResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GetConsensusCommitResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t commit_;
    ::int64_t term_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_qdrant_5finternal_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GetConsensusCommitResponse_class_data_;
// -------------------------------------------------------------------

class GetConsensusCommitRequest final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:qdrant.GetConsensusCommitRequest) */ {
 public:
  inline GetConsensusCommitRequest() : GetConsensusCommitRequest(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GetConsensusCommitRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GetConsensusCommitRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetConsensusCommitRequest(::google::protobuf::internal::ConstantInitialized);

  inline GetConsensusCommitRequest(const GetConsensusCommitRequest& from) : GetConsensusCommitRequest(nullptr, from) {}
  inline GetConsensusCommitRequest(GetConsensusCommitRequest&& from) noexcept
      : GetConsensusCommitRequest(nullptr, ::std::move(from)) {}
  inline GetConsensusCommitRequest& operator=(const GetConsensusCommitRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetConsensusCommitRequest& operator=(GetConsensusCommitRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetConsensusCommitRequest& default_instance() {
    return *reinterpret_cast<const GetConsensusCommitRequest*>(
        &_GetConsensusCommitRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(GetConsensusCommitRequest& a, GetConsensusCommitRequest& b) { a.Swap(&b); }
  inline void Swap(GetConsensusCommitRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetConsensusCommitRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetConsensusCommitRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<GetConsensusCommitRequest>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const GetConsensusCommitRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const GetConsensusCommitRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "qdrant.GetConsensusCommitRequest"; }

  explicit GetConsensusCommitRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GetConsensusCommitRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GetConsensusCommitRequest& from);
  GetConsensusCommitRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GetConsensusCommitRequest&& from) noexcept
      : GetConsensusCommitRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:qdrant.GetConsensusCommitRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_qdrant_5finternal_5fservice_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GetConsensusCommitRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GetConsensusCommitRequest

// -------------------------------------------------------------------

// GetConsensusCommitResponse

// int64 commit = 1;
inline void GetConsensusCommitResponse::clear_commit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.commit_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int64_t GetConsensusCommitResponse::commit() const {
  // @@protoc_insertion_point(field_get:qdrant.GetConsensusCommitResponse.commit)
  return _internal_commit();
}
inline void GetConsensusCommitResponse::set_commit(::int64_t value) {
  _internal_set_commit(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:qdrant.GetConsensusCommitResponse.commit)
}
inline ::int64_t GetConsensusCommitResponse::_internal_commit() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.commit_;
}
inline void GetConsensusCommitResponse::_internal_set_commit(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.commit_ = value;
}

// int64 term = 2;
inline void GetConsensusCommitResponse::clear_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int64_t GetConsensusCommitResponse::term() const {
  // @@protoc_insertion_point(field_get:qdrant.GetConsensusCommitResponse.term)
  return _internal_term();
}
inline void GetConsensusCommitResponse::set_term(::int64_t value) {
  _internal_set_term(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:qdrant.GetConsensusCommitResponse.term)
}
inline ::int64_t GetConsensusCommitResponse::_internal_term() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.term_;
}
inline void GetConsensusCommitResponse::_internal_set_term(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = value;
}

// -------------------------------------------------------------------

// WaitOnConsensusCommitRequest

// int64 commit = 1;
inline void WaitOnConsensusCommitRequest::clear_commit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.commit_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int64_t WaitOnConsensusCommitRequest::commit() const {
  // @@protoc_insertion_point(field_get:qdrant.WaitOnConsensusCommitRequest.commit)
  return _internal_commit();
}
inline void WaitOnConsensusCommitRequest::set_commit(::int64_t value) {
  _internal_set_commit(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:qdrant.WaitOnConsensusCommitRequest.commit)
}
inline ::int64_t WaitOnConsensusCommitRequest::_internal_commit() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.commit_;
}
inline void WaitOnConsensusCommitRequest::_internal_set_commit(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.commit_ = value;
}

// int64 term = 2;
inline void WaitOnConsensusCommitRequest::clear_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int64_t WaitOnConsensusCommitRequest::term() const {
  // @@protoc_insertion_point(field_get:qdrant.WaitOnConsensusCommitRequest.term)
  return _internal_term();
}
inline void WaitOnConsensusCommitRequest::set_term(::int64_t value) {
  _internal_set_term(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:qdrant.WaitOnConsensusCommitRequest.term)
}
inline ::int64_t WaitOnConsensusCommitRequest::_internal_term() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.term_;
}
inline void WaitOnConsensusCommitRequest::_internal_set_term(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = value;
}

// int64 timeout = 3;
inline void WaitOnConsensusCommitRequest::clear_timeout() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timeout_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int64_t WaitOnConsensusCommitRequest::timeout() const {
  // @@protoc_insertion_point(field_get:qdrant.WaitOnConsensusCommitRequest.timeout)
  return _internal_timeout();
}
inline void WaitOnConsensusCommitRequest::set_timeout(::int64_t value) {
  _internal_set_timeout(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:qdrant.WaitOnConsensusCommitRequest.timeout)
}
inline ::int64_t WaitOnConsensusCommitRequest::_internal_timeout() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timeout_;
}
inline void WaitOnConsensusCommitRequest::_internal_set_timeout(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timeout_ = value;
}

// -------------------------------------------------------------------

// WaitOnConsensusCommitResponse

// bool ok = 1;
inline void WaitOnConsensusCommitResponse::clear_ok() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ok_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline bool WaitOnConsensusCommitResponse::ok() const {
  // @@protoc_insertion_point(field_get:qdrant.WaitOnConsensusCommitResponse.ok)
  return _internal_ok();
}
inline void WaitOnConsensusCommitResponse::set_ok(bool value) {
  _internal_set_ok(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:qdrant.WaitOnConsensusCommitResponse.ok)
}
inline bool WaitOnConsensusCommitResponse::_internal_ok() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ok_;
}
inline void WaitOnConsensusCommitResponse::_internal_set_ok(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ok_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace qdrant


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // qdrant_5finternal_5fservice_2eproto_2epb_2eh
